version: '3.9'

services:
  rest-api:
    image: django-rest-api 
    container_name: taller-jwt-rest 
    build: 
      context: . 
      dockerfile: Dockerfile 
    ports:
      - 8000:8000
    expose:
      - 8000
    volumes:
      - .:/app/ 
    command: python manage.py runserver 0.0.0.0:8000

networks:
  default:
    name: development
    external: true